name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        working-directory: ./testeReact3   # <- pasta do seu React
        run: npm install

      - name: Rodar testes
        working-directory: ./testeReact3
        run: npm test -- --watchAll=false

      - name: Build aplicação
        working-directory: ./testeReact3
        run: npm run build
